```python
import re
from datetime import datetime
import os
import logging
from typing import List, Dict

# Assuming these functions are defined elsewhere or imported
def delegate_to_rtx(error_info: str) -> str:
    # Placeholder for the actual implementation
    return "Fix code generated by RTX"

def check_logs_for_errors() -> List[Dict]:
    log_files = ["ai_gateway.log", "rtx_agent.log", "autonomous/rtx_log.txt"]
    errors = []
    
    for file in log_files:
        with open(file, 'r') as f:
            content = f.read()
            if re.search(r'(Traceback|Exception|Error|[ERROR]|[CRITICAL])', content):
                lines = content.split('\n')
                for line_num, line in enumerate(lines):
                    if any(error_keyword in line for error_keyword in ['Traceback', 'Exception', 'Error', '[ERROR]', '[CRITICAL]']):
                        errors.append({
                            "file": file,
                            "line": line_num + 1,
                            "error_text": line.strip(),
                            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                        })
    return errors

def auto_fix_error(error_info: Dict) -> Dict:
    fix_code = delegate_to_rtx(error_info["error_text"])
    explanation = f"Proposed fix for error in {error_info['file']} at line {error_info['line']}: {fix_code}"
    confidence = 0.8  # Placeholder value, should be calculated based on RTX analysis
    return {
        "fix_code": fix_code,
        "explanation": explanation,
        "confidence": confidence
    }

def apply_fix(fix_info: Dict) -> str:
    try:
        with open(os.path.join("autonomous", error_info["file"]), 'a') as f:
            f.write("\n" + fix_info["fix_code"])
        logging.info(fixed)
        return "success"
    except Exception as e:
        logging.error(f"Failed to apply fix: {e}")
        return "failure"

def main():
    while True:
        errors = check_logs_for_errors()
        if errors:
            for error in errors:
                fix_info = auto_fix_error(error)
                if fix_info["confidence"] > 0.8:
                    result = apply_fix(fix_info)
                    logging.info(f"Applied fix: {fix_info['explanation']} - Result: {result}")
        # Placeholder for the rest of the main loop
        # Perform other tasks and then sleep or wait for next iteration

if __name__ == "__main__":
    logging.basicConfig(filename='autonomous/fixes.log', level=logging.INFO)
    main()
```

This code snippet integrates error detection, auto-fix proposal, and fix application into a main loop. The `check_logs_for_errors` function scans the specified log files for errors, while `auto_fix_error` generates a proposed fix based on the error text. Finally, `apply_fix` writes the fix to the file if it is deemed confident enough. All actions are logged to `autonomous/fixes.log`.